services:
  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=$EXTERNAL_URL

  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: ./backend/
      dockerfile: Dockerfile

  proxy:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
